version: '3'

services:

  nginx:
    build:
      context: docker/nginx
    container_name: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/${DOMAIN}
      - ./logs/nginx:/var/log/nginx
    ports:
      - '80:80'
    depends_on:
      - php-fpm
    networks:
      bitrix:
        ipv4_address: ${NGINX_INTERFACE}

  php-fpm:
    build:
      context: docker/php-fpm
    container_name: php-fpm
    volumes:
      - ./public:/var/www/${DOMAIN}
      - ./logs/php:/var/log/php/
    environment:
      - PHP_IDE_CONFIG=serverName=${DOMAIN}
    depends_on:
      - mysql
    networks:
      - bitrix
    extra_hosts:
      - "${DOMAIN}:${NGINX_INTERFACE}"

  mysql:
    build:
      context: docker/mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./logs/mysql:/var/log/mysql
      - ./storage/mysql/:/var/lib/mysql
      - ./storage/backup:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - bitrix

  memcached:
    build:
      context: docker/memcached
    volumes:
      - ./storage/memcached:/var/lib/memcached
    ports:
      - "11211:11211"
    depends_on:
      - php-fpm
    networks:
      - bitrix

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - bitrix

  adminer:
    image: dockette/adminer:full
    container_name: adminer
    links:
      - mysql:mysql
    ports:
      - '8080:80'

networks:
  bitrix:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.100.0.0/24